name: Build & Push to Container Registry

permissions:
    contents: read
    packages: write

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repo
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate Docker image metadata
              uses: docker/metadata-action@v5
              id: img_meta
              with:
                flavor: |
                    latest=auto
                images: ghcr.io/${{ github.repository }}
                tags: |
                    type=ref,event=branch
                    type=sha,prefix=,suffix=,format=short

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                  file: Dockerfile
                  context: ./
                  platforms: linux/amd64
                  tags: ${{ steps.img_meta.outputs.tags }}
                  labels: ${{ steps.img_meta.outputs.labels }}
                  push: true
