name: Build & Push to Container Registry

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master

jobs:
  docker:
    uses: kakushindev/workflows/.github/workflows/build-docker-image.yml@main
    secrets: inherit
    